## This rule redirects to my Telegram Channel
[[redirects]]
  from = "/telegram"
  to = "https://t.me/obetomuniz"
  status = 301
  force = true # COMMENT: ensure that we always redirect

## This rule redirects to my Newsletter 
[[redirects]]
  from = "/newsletter"
  to = "https://landing.mailerlite.com/webforms/landing/y9t5l3"
  status = 301
  force = true # COMMENT: ensure that we always redirect

## This rule redirects to my YouTube 
[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/c/betomuniz"
  status = 301
  force = true # COMMENT: ensure that we always redirect

## This rule redirects to my Instagram 
[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/obetomuniz/"
  status = 301
  force = true # COMMENT: ensure that we always redirect

## This rule redirects to my GitHub 
[[redirects]]
  from = "/github"
  to = "https://github.com/obetomuniz"
  status = 301
  force = true # COMMENT: ensure that we always redirect

## This rule redirects to my LinkedIn 
[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/obetomuniz"
  status = 301
  force = true # COMMENT: ensure that we always redirect

## This rule redirects to my TikTok 
[[redirects]]
  from = "/tiktok"
  to = "https://www.tiktok.com/@obetomuniz"
  status = 301
  force = true # COMMENT: ensure that we always redirect

## This rule redirects to my Twitter 
[[redirects]]
  from = "/twitter"
  to = "https://github.com/twitter"
  status = 301
  force = true # COMMENT: ensure that we always redirect