export const DEFAULT_BACKGROUND_COLOR = "#fff"
export const DEFAULT_TEXT_OPACITY = "0.6"
export const DEFAULT_TEXT_COLOR = "#000"
export const DEFAULT_LINK_COLOR = "#000"
export const DEFAULT_LINK_COLOR_ACTIVE = "darkblue"
export const DEFAULT_LINK_COLOR_HOVER = "darkblue"
export const DEFAULT_BOX_SHADOW_COLOR = "#bbb"

export const DEFAULT_POST_TITLE_COLOR = "darkblue"
export const DEFAULT_POST_TEXT_COLOR = "#000"
export const DEFAULT_POST_CODE_BACKGROUND_COLOR = "#eee"
export const DEFAULT_POST_CODE_TEXT_COLOR = "#000"
export const DEFAULT_POST_LIST_ITEM_COLOR = "#000"
export const DEFAULT_POST_BLOCKQUOTE_COLOR = "#000"
export const DEFAULT_POST_CODE_DEMO_BACKGROUND = "rgb(45, 45, 45)"
export const DEFAULT_POST_HR_COLOR = "#ccc"
