export const DEFAULT_BACKGROUND_COLOR = "#1f1f1f"
export const DEFAULT_TEXT_OPACITY = "1"
export const DEFAULT_TEXT_COLOR = "#fff"
export const DEFAULT_LINK_COLOR = "#fff"
export const DEFAULT_LINK_COLOR_ACTIVE = "lightskyblue"
export const DEFAULT_LINK_COLOR_HOVER = "lightskyblue"
export const DEFAULT_BOX_SHADOW_COLOR = "#000"

export const DEFAULT_PROJECT_GITHUB_COLOR = "#eee"

export const DEFAULT_POST_TITLE_COLOR = "lightskyblue"
export const DEFAULT_POST_TEXT_COLOR = "#fff"
export const DEFAULT_POST_CODE_BACKGROUND_COLOR = "#eee"
export const DEFAULT_POST_CODE_TEXT_COLOR = "#000"
export const DEFAULT_POST_LIST_ITEM_COLOR = "#fff"
export const DEFAULT_POST_BLOCKQUOTE_COLOR = "#fff"
export const DEFAULT_POST_BLOCKQUOTE_TEXT_COLOR = "#fff"
export const DEFAULT_POST_CODE_DEMO_BACKGROUND = "rgb(45, 45, 45)"
export const DEFAULT_POST_HR_COLOR = "#fff"
