backend:
  name: git-gateway
  repo: https://github.com/obetomuniz/betomuniz.com
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/uploads/
public_folder: /uploads/

collections:
  - name: "blog"
    extension: "mdx"
    format: "frontmatter"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Body", name: "body", widget: "mdx" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Keywords", name: "keywords", widget: "list" }
      - { label: "Category", name: "category", widget: "string" }
  - name: "drops"
    extension: "mdx"
    format: "frontmatter"
    label: "Drops"
    folder: "src/pages/drops"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "drop-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Body", name: "body", widget: "mdx" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Keywords", name: "keywords", widget: "list" }
      - { label: "Category", name: "category", widget: "string" }
