backend:
  name: git-gateway
  repo: https://github.com/obetomuniz/betomuniz.com
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

publish_mode: editorial_workflow

media_folder: static/uploads/
public_folder: /uploads/

media_library:
  name: cloudinary
  config:
    cloud_name: ${{ secrets.CLOUDINARY_API_KEY }}
    api_key: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
    multiple: true
    - fetch_format: auto
      quality: auto
      width: 400
      crop: scale

collections:
  - name: "blog"
    extension: "mdx"
    format: "frontmatter"
    label: "Blog"
    folder: "src/content/posts"
    create: true
    slug: "{{fields.slug}}"
    preview_path: "blog/{{fields.slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern:
            [
              "^[a-z0-9]+(?:-[a-z0-9]+)*$",
              "A slug can have no spaces or special characters",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "mdx" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured", name: "featured", widget: image, required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Keywords", name: "keywords", widget: "list" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Language", name: "lang", widget: "string" }
      - {
          label: "Is External?",
          name: "external",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "External Link",
          name: "externalLink",
          widget: "string",
          required: false,
        }
  - name: "drops"
    extension: "mdx"
    format: "frontmatter"
    label: "Drops"
    folder: "src/content/drops"
    create: true
    slug: "{{fields.slug}}"
    preview_path: "drops/{{fields.slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "drop-post",
        }
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          pattern:
            [
              "^[a-z0-9]+(?:-[a-z0-9]+)*$",
              "A slug can have no spaces or special characters",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Subtitle",
          name: "subtitle",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: "mdx" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured", name: "featured", widget: image, required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Keywords", name: "keywords", widget: "list" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Language", name: "lang", widget: "string" }
      - {
          label: "Is External?",
          name: "external",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "External Link",
          name: "externalLink",
          widget: "string",
          required: false,
        }
