import { createGlobalStyle } from "styled-components"

export const LightThemeStyle = createGlobalStyle`
  :root {
    /* UI */
    --DEFAULT_BORDER_RADIUS: 5px;
    --DEFAULT_MARGIN: 5rem;
    --DEFAULT_MARGIN_MOBILE: 4.5rem;
    --DEFAULT_POST_MARGIN_BOTTOM: 1.8rem;
    --DEFAULT_POST_MARGIN_BOTTOM_MOBILE: 1.5rem;

    /* Colors */
    --DEFAULT_BACKGROUND_COLOR: #fff;
    --DEFAULT_TEXT_OPACITY: 0.6;
    --DEFAULT_TEXT_COLOR: #000;
    --DEFAULT_LINK_COLOR: #000;
    --DEFAULT_LINK_COLOR_ACTIVE: darkblue;
    --DEFAULT_LINK_COLOR_HOVER: darkblue;
    --DEFAULT_BOX_SHADOW_COLOR: #bbb;

    --DEFAULT_HEADER_PHOTO_BORDER_COLOR: blueviolet;

    --DEFAULT_COMMUNITY_CATEGORY_COLOR: deeppink;
    --DEFAULT_TECH_CATEGORY_COLOR: darkgreen;
    --DEFAULT_DEV_LIFESTYLE_COLOR: goldenrod;
    --DEFAULT_REMOTE_WORK_CATEGORY_COLOR: dodgerblue;

    --DEFAULT_PROJECT_GITHUB_COLOR: #000;
      
    --DEFAULT_DETAIL_COLOR: darkblue;

    --DEFAULT_POST_TITLE_COLOR: darkblue;
    --DEFAULT_POST_TEXT_COLOR: #000;
    --DEFAULT_POST_CODE_BACKGROUND_COLOR: #eee;
    --DEFAULT_POST_CODE_TEXT_COLOR: #000;
    --DEFAULT_POST_LIST_ITEM_COLOR: #000;
    --DEFAULT_POST_BLOCKQUOTE_COLOR: #000;
    --DEFAULT_POST_BLOCKQUOTE_TEXT_COLOR: #000;
    --DEFAULT_POST_CODE_DEMO_BACKGROUND: rgb(45, 45, 45);
    --DEFAULT_POST_HR_COLOR: #ccc;

    /* Typo */
    --DEFAULT_SERIF_FONTS: medium-content-serif-font, Georgia, Cambria, "Times New Roman", Times, serif;
    --DEFAULT_SAN_SERIF_FONTS: medium-content-sans-serif-font, "Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", Geneva, Arial, sans-serif;
    --DEFAULT_CODE_FONTS: "Courier New", serif;

    --DEFAULT_NAV_ITEM_FONT_SIZE: 1rem;
    --DEFAULT_NAV_ITEM_TEXT_SHADOW: 1px 1px 1px #ddd;

    --DEFAULT_ABOUT_FONT_SIZE: 1.5rem;
    --DEFAULT_ABOUT_FONT_SIZE_MOBILE: 1.09rem;
    --DEFAULT_ABOUT_LINE_HEIGHT: 2.5rem;
    --DEFAULT_ABOUT_LINE_HEIGHT_MOBILE: 1.5rem;

    --DEFAULT_LIST_ITEM_LABEL_FONT_SIZE: 1.5rem;
    --DEFAULT_LIST_ITEM_LABEL_FONT_SIZE_MOBILE: 1rem;
    --DEFAULT_LIST_ITEM_LABEL_LINE_HEIGHT: 2.5rem;
    --DEFAULT_LIST_ITEM_LABEL_LINE_HEIGHT_MOBILE: 1.5rem;

    --DEFAULT_LIST_ITEM_DETAIL_FONT_SIZE: 0.8rem;
    --DEFAULT_LIST_ITEM_DETAIL_FONT_SIZE_MOBILE: 0.6rem;

    --DEFAULT_POST_TITLE_FONT_FAMILY: var(--DEFAULT_SAN_SERIF_FONTS);
    --DEFAULT_POST_TITLE_FONT_SIZE: 2.5rem;
    --DEFAULT_POST_TITLE_FONT_SIZE_MOBILE: 1.1rem;
    --DEFAULT_POST_TITLE_LINE_HEIGHT: 4rem;
    --DEFAULT_POST_TITLE_LINE_HEIGHT_MOBILE: 2rem;

    --DEFAULT_POST_SUBTITLE_FONT_SIZE: 1.9rem;
    --DEFAULT_POST_SUBTITLE_FONT_SIZE_MOBILE: 0.9rem;

    --DEFAULT_POST_REGISTER_FONT_SIZE: 0.8rem;
    --DEFAULT_POST_REGISTER_FONT_SIZE_MOBILE: 0.7rem;

    --DEFAULT_POST_TEXT_LETTER_SPACING: 0.01rem;
    --DEFAULT_POST_TEXT_LETTER_SPACING_MOBILE: 0.02rem;
    --DEFAULT_POST_TEXT_FONT_SIZE: 1.15rem;
    --DEFAULT_POST_TEXT_FONT_SIZE_MOBILE: 0.9rem;
    --DEFAULT_POST_TEXT_LINE_HEIGHT: 1.8rem;
    --DEFAULT_POST_TEXT_LINE_HEIGHT_MOBILE: 1.2rem;

    --DEFAULT_POST_SMALL_TEXT_FONT_SIZE: 0.7rem;
    --DEFAULT_POST_SMALL_TEXT_FONT_SIZE_MOBILE: 0.7rem;
    --DEFAULT_POST_SMALL_TEXT_LINE_HEIGHT: 1.4rem;
    --DEFAULT_POST_SMALL_TEXT_LINE_HEIGHT_MOBILE: 1.2rem;

    --DEFAULT_POST_SECONDARY_TITLE_LINE_HEIGHT: 2.3rem;
    --DEFAULT_POST_SECONDARY_TITLE_LINE_HEIGHT_MOBILE: 2rem;

    --DEFAULT_POST_H2_FONT_SIZE: 2.1rem;
    --DEFAULT_POST_H2_FONT_SIZE_MOBILE: 2rem;
    --DEFAULT_POST_H3_FONT_SIZE: 1.8rem;
    --DEFAULT_POST_H3_FONT_SIZE_MOBILE: 1.7rem;
    --DEFAULT_POST_H4_FONT_SIZE: 1.5rem;
    --DEFAULT_POST_H4_FONT_SIZE_MOBILE: 1.4rem;

    --DEFAULT_POST_LIST_ITEM_FONT_SIZE: 1rem;
    --DEFAULT_POST_LIST_ITEM_FONT_SIZE_MOBILE: 0.9rem;
    --DEFAULT_POST_LIST_ITEM_LINE_HEIGHT: 1.5rem;
    --DEFAULT_POST_LIST_ITEM_LINE_HEIGHT_MOBILE: 1.5rem;

    --DEFAULT_POST_CODE_DEMO_FONT_SIZE: 0.9rem;
    --DEFAULT_POST_CODE_DEMO_FONT_SIZE_MOBILE: 0.7rem;
    --DEFAULT_POST_CODE_DEMO_LINE_HEIGHT: 1.2rem;
    --DEFAULT_POST_CODE_DEMO_LINE_HEIGHT_MOBILE: 1rem;
  }
`

export const DarkThemeStyle = createGlobalStyle`
  @media (prefers-color-scheme: dark) {
    :root {
      /* UI */
      --DEFAULT_BORDER_RADIUS: 5px;
      --DEFAULT_MARGIN: 5rem;
      --DEFAULT_MARGIN_MOBILE: 4.5rem;
      --DEFAULT_POST_MARGIN_BOTTOM: 1.8rem;
      --DEFAULT_POST_MARGIN_BOTTOM_MOBILE: 1.5rem;

      /* Colors */
      --DEFAULT_BACKGROUND_COLOR: #1f1f1f;
      --DEFAULT_TEXT_OPACITY: 1;
      --DEFAULT_TEXT_COLOR: #fff;
      --DEFAULT_LINK_COLOR: #fff;
      --DEFAULT_LINK_COLOR_ACTIVE: lightskyblue;
      --DEFAULT_LINK_COLOR_HOVER: lightskyblue;
      --DEFAULT_BOX_SHADOW_COLOR: #000;

      --DEFAULT_HEADER_PHOTO_BORDER_COLOR: darkviolet;

      --DEFAULT_COMMUNITY_CATEGORY_COLOR: deeppink;
      --DEFAULT_TECH_CATEGORY_COLOR: limegreen;
      --DEFAULT_DEV_LIFESTYLE_COLOR: gold;
      --DEFAULT_REMOTE_WORK_CATEGORY_COLOR: deepskyblue;
      
      --DEFAULT_PROJECT_GITHUB_COLOR: #eee;
      
      --DEFAULT_DETAIL_COLOR: lightblue;

      --DEFAULT_POST_TITLE_COLOR: lightskyblue;
      --DEFAULT_POST_TEXT_COLOR: #fff;
      --DEFAULT_POST_CODE_BACKGROUND_COLOR: #eee;
      --DEFAULT_POST_CODE_TEXT_COLOR: #000;
      --DEFAULT_POST_LIST_ITEM_COLOR: #fff;
      --DEFAULT_POST_BLOCKQUOTE_COLOR: #fff;
      --DEFAULT_POST_BLOCKQUOTE_TEXT_COLOR: #fff;
      --DEFAULT_POST_CODE_DEMO_BACKGROUND: rgb(45, 45, 45);
      --DEFAULT_POST_HR_COLOR: #fff;

      /* Typo */
      --DEFAULT_SERIF_FONTS: medium-content-serif-font, Georgia, Cambria, "Times New Roman", Times, serif;
      --DEFAULT_SAN_SERIF_FONTS: medium-content-sans-serif-font, "Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", Geneva, Arial, sans-serif;
      --DEFAULT_CODE_FONTS: "Courier New", serif;

      --DEFAULT_NAV_ITEM_FONT_SIZE: 1rem;
      --DEFAULT_NAV_ITEM_TEXT_SHADOW: 2px 2px 2px #000;

      --DEFAULT_ABOUT_FONT_SIZE: 1.5rem;
      --DEFAULT_ABOUT_FONT_SIZE_MOBILE: 1.09rem;
      --DEFAULT_ABOUT_LINE_HEIGHT: 2.5rem;
      --DEFAULT_ABOUT_LINE_HEIGHT_MOBILE: 1.5rem;

      --DEFAULT_LIST_ITEM_LABEL_FONT_SIZE: 1.5rem;
      --DEFAULT_LIST_ITEM_LABEL_FONT_SIZE_MOBILE: 1rem;
      --DEFAULT_LIST_ITEM_LABEL_LINE_HEIGHT: 2.5rem;
      --DEFAULT_LIST_ITEM_LABEL_LINE_HEIGHT_MOBILE: 1.5rem;

      --DEFAULT_LIST_ITEM_DETAIL_FONT_SIZE: 0.8rem;
      --DEFAULT_LIST_ITEM_DETAIL_FONT_SIZE_MOBILE: 0.6rem;

      --DEFAULT_POST_TITLE_FONT_FAMILY: var(--DEFAULT_SERIF_FONTS);
      --DEFAULT_POST_TITLE_FONT_SIZE: 2.5rem;
      --DEFAULT_POST_TITLE_FONT_SIZE_MOBILE: 2.1rem;
      --DEFAULT_POST_TITLE_LINE_HEIGHT: 4rem;
      --DEFAULT_POST_TITLE_LINE_HEIGHT_MOBILE: 2.5rem;

      --DEFAULT_POST_SUBTITLE_FONT_SIZE: 1.9rem;
      --DEFAULT_POST_SUBTITLE_FONT_SIZE_MOBILE: 1.1rem;

      --DEFAULT_POST_REGISTER_FONT_SIZE: 0.8rem;
      --DEFAULT_POST_REGISTER_FONT_SIZE_MOBILE: 0.7rem;

      --DEFAULT_POST_TEXT_LETTER_SPACING: 0.01rem;
      --DEFAULT_POST_TEXT_LETTER_SPACING_MOBILE: 0.02rem;
      --DEFAULT_POST_TEXT_FONT_SIZE: 1.15rem;
      --DEFAULT_POST_TEXT_FONT_SIZE_MOBILE: 0.9rem;
      --DEFAULT_POST_TEXT_LINE_HEIGHT: 1.8rem;
      --DEFAULT_POST_TEXT_LINE_HEIGHT_MOBILE: 1.2rem;

      --DEFAULT_POST_SMALL_TEXT_FONT_SIZE: 0.7rem;
      --DEFAULT_POST_SMALL_TEXT_FONT_SIZE_MOBILE: 0.7rem;
      --DEFAULT_POST_SMALL_TEXT_LINE_HEIGHT: 1.4rem;
      --DEFAULT_POST_SMALL_TEXT_LINE_HEIGHT_MOBILE: 1.2rem;

      --DEFAULT_POST_SECONDARY_TITLE_LINE_HEIGHT: 2.3rem;
      --DEFAULT_POST_SECONDARY_TITLE_LINE_HEIGHT_MOBILE: 2rem;

      --DEFAULT_POST_H2_FONT_SIZE: 2.1rem;
      --DEFAULT_POST_H2_FONT_SIZE_MOBILE: 1.8rem;
      --DEFAULT_POST_H3_FONT_SIZE: 1.8rem;
      --DEFAULT_POST_H3_FONT_SIZE_MOBILE: 1.5rem;
      --DEFAULT_POST_H4_FONT_SIZE: 1.5rem;
      --DEFAULT_POST_H4_FONT_SIZE_MOBILE: 1.2rem;

      --DEFAULT_POST_LIST_ITEM_FONT_SIZE: 1rem;
      --DEFAULT_POST_LIST_ITEM_FONT_SIZE_MOBILE: 0.9rem;
      --DEFAULT_POST_LIST_ITEM_LINE_HEIGHT: 1.5rem;
      --DEFAULT_POST_LIST_ITEM_LINE_HEIGHT_MOBILE: 1.5rem;

      --DEFAULT_POST_CODE_DEMO_FONT_SIZE: 0.9rem;
      --DEFAULT_POST_CODE_DEMO_FONT_SIZE_MOBILE: 0.7rem;
      --DEFAULT_POST_CODE_DEMO_LINE_HEIGHT: 1.2rem;
      --DEFAULT_POST_CODE_DEMO_LINE_HEIGHT_MOBILE: 1rem;
    }
  }
`
