---
label: Site Config
hide_body: true
fields:
- name: config_site_name
  type: text
  config:
    required: false
  label: Site Name
  default: Beto Muniz
- name: config_site_url
  type: text
  config:
    required: false
  label: Site URL
  default: https://betomuniz.com
- name: config_site_username
  type: text
  config:
    required: false
  label: Site Username
  default: obetomuniz
- name: config_google_analytics_id
  type: text
  config:
    required: false
  label: Google Analytics ID
- name: config_gravatar
  type: text
  config:
    required: false
  label: Gravatar
  default: https://www.gravatar.com/avatar/fff7258836f20ea66b061b49a51fe8dd?s=170
